function grafico_5(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 08-May-2021 16:31:21

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'MarkerFaceColor',[0 1 1],'Marker','diamond','LineStyle','none',...
    'Color',[0 0 1]);

% Create ylabel
ylabel({'escala logaritmica'});

% Create xlabel
xlabel({'x'});

% Create title
title({'escala logaritmica de c(x) = 2e2x+3'});

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
