function grafico_4(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 08-May-2021 16:28:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create semilogy
semilogy(X1,Y1,'Marker','*','Color',[1 0.411764705882353 0.16078431372549]);

% Create ylabel
ylabel({'c(x)'});

% Create xlabel
xlabel({'X'});

% Create title
title({'c(x) = 2e^(^2^x^+^3^)'});

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'GridAlpha',0.2,'GridColor',...
    [0.0509803921568627 0.0509803921568627 0.0509803921568627],...
    'MinorGridLineStyle','-','TickLength',[0.05 0.025],'XGrid','on','YGrid',...
    'on','YMinorTick','on','YScale','log','YTick',...
    [1e-10 1e-05 1 100000 10000000000]);
