function grafico_3(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-May-2021 15:28:08

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineStyle','none');
set(plot1(1),'DisplayName','a(x)','Marker','*','Color',[1 0 0]);
set(plot1(2),'DisplayName','b(x)','Marker','+','Color',[0 1 0]);

% Create ylabel
ylabel({'a(x) y b(x)'});

% Create xlabel
xlabel({'X'});

% Create title
title({'Comparación de dos funciones'});

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.749880951291039 0.754365077548557 0.12821428659984 0.0869047637212845]);

